---
services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres

  redis:
    image: "redis:latest"

  cf_server:
    depends_on:
      - postgres
      - redis
      - cf_worker
    build:
      context: ./complex-fibonacci_server
      dockerfile: dockerfile.dev
    volumes:
      - /app/node_modules
      - ./complex-fibonacci_server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PG_USER=postgres
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_DATABASE=postgres
      - PG_PASSWORD=postgres

  cf_client:
      depends_on:
        - cf_server
      build:
        context: ./complex-fibonacci_client
        dockerfile: dockerfile.dev
      volumes:
        - /app/node_modules
        - ./complex-fibonacci_client:/app

  cf_worker:
      depends_on:
        - redis
      build:
        context: ./complex-fibonacci_worker
        dockerfile: dockerfile.dev
      volumes:
        - /app/node_modules
        - ./complex-fibonacci_worker:/app
      environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379
  
  cf_nginx:
      restart: unless-stopped
      depends_on:
        - cf_client
        - cf_server
      build:
        context: ./complex-fibonacci_nginx
        dockerfile: dockerfile.dev
      ports:
       - '80:80'
       - '5173:5173'