name: Deploy Multicontainer
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build dev image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/complex-fibonacci_client_tests -f ./complex-fibonacci_client/dockerfile.dev ./complex-fibonacci_client

      - name: Run tests
        run: docker run -e -CI=true ${{ secrets.DOCKERHUB_USERNAME }}/complex-fibonacci_client_tests npm run test:coverage

  docker_build_and_push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push client
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./complex-fibonacci_client
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/complex-fibonacci_client

      - name: Build and push server
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./complex-fibonacci_server
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/complex-fibonacci_server

      - name: Build and push worker
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./complex-fibonacci_worker
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/complex-fibonacci_worker

      - name: Build and push nginx
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./complex-fibonacci_nginx
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/complex-fibonacci_nginx

  deploy_to_eb:
    runs-on: ubuntu-latest
    needs: docker_build_and_push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git'
  
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-2
          application_name: complex-fibonacci
          environment_name: Complex-fibonacci-env
          existing_bucket_name: elasticbeanstalk-us-east-2-572263478950
          deployment_package: deploy.zip
          version_label: ${{ github.sha }}